---
# Main Ansible orchestrator
# (Design only â€“ no execution yet)

- hosts: all
  roles:
    - common

- hosts: jenkins
  roles:
    - jenkins

- hosts: ansible
  roles:
    - eks-access
    - helm

